baseURL = "https://countryhillestates.netlify.com/"
languageCode = "en-us"
title = "Country Hill Estates"

[params]
description = "A site dedicated to the community of Country Hill Estates."

[menu]

  [[menu.main]]
    identifier = "phases"
    name = "Phases"
    weight = 1

  [[menu.main]]
    identifier = "association"
    name = "Association"
    weight = 2

  [[menu.main]]
    identifier = "resources"
    name = "Resources"
    weight = 3
    url = "/pages/resources"

  [[menu.main]]
    identifier = "contactus"
    name = "Contact Us"
    weight = 4
    url = "/pages/contact-us"

  [[menu.main]]
    name = "Communications"
    parent = "association"
    url = "/pages/communications"

  [[menu.main]]
    name = "ByLaws"
    parent = "association"
    url = "/pages/bylaws"

  [[menu.main]]
    name = "Phase 1"
    parent = "phases"
    url = "/phases/1"

  [[menu.main]]
    name = "Phase 2"
    parent = "phases"
    url = "/phases/2"

  [[menu.main]]
    name = "Phase 3"
    parent = "phases"
    url = "/phases/3"
